server:
  port: 8080
  servlet:
    session:
      timeout: 30m
management:
  endpoint:
    health:
      show-details: always
vaadin:
  servlet:
    production-mode: true
    close-idle-sessions: false
jwt:
  secret : ${JWT_SECRET}
football:
  service:
    endpoints:
      login: ${BASE_URL}/login
      tournament: ${BASE_URL}/tournaments
      invitation: ${BASE_URL}/invitations
      register: ${BASE_URL}/signup
      user: ${BASE_URL}/users
      prediction: ${BASE_URL}/predictions
      points: ${BASE_URL}/points