server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
vaadin:
  servlet:
    production-mode: true
    close-idle-sessions: true
jwt:
  secret : ${JWT_SECRET}
football:
  service:
    endpoints:
      login: ${BASE_URL}/login
      tournament: ${BASE_URL}/tournaments
      invitation: ${BASE_URL}/invitations